---
- name: System setup
  hosts: common
  roles: 
    - role: common
- name: Create lvm disk on common
  hosts: common
  roles:
    - role: lvm
      lvm_disk:
        - { vgname: 'vg0', disk: 'disklvm1', dev: '/dev/sdb', fstype: 'xfs', mount_dir: '/data'}
    - role: nodejs
    - role: mysql
      mysql_dir: /data/mysql
    - role: pika
      pika_dir: /data/pika
    - role: nginx
      ip_fix: 127.0.0.
      install_dir: /data/nginx

