nginx_disk:
  - { vgname: 'vg0', disk: 'disklvm1', dev: '/dev/sdb', fstype: 'xfs', mount_dir: '/nginx'}

game_disk:
  - { vgname: 'vg0', disk: 'disklvm1', dev: '/dev/sdb', fstype: 'xfs', mount_dir: '/game'}

bgame_disk:
  - { vgname: 'vg0', disk: 'disklvm1', dev: '/dev/sdb', fstype: 'ext4', mount_dir: '/game'}

tj_disk:
  - { vgname: 'vg0', disk: 'disklvm1', dev: '/dev/sdb', fstype: 'xfs', mount_dir: '/game'}
  - { vgname: 'vg1', disk: 'disklvm2', dev: '/dev/sdc', fstype: 'xfs', mount_dir: '/db/redis'}


db_disk:
  - { vgname: 'vg0', disk: 'disklvm1', dev: '/dev/sdb', fstype: 'xfs', mount_dir: '/db/mysql/data'}
  - { vgname: 'vg1', disk: 'disklvm2', dev: '/dev/sdc', fstype: 'xfs', mount_dir: '/db/mysql/binlog'}
  - { vgname: 'vg2', disk: 'disklvm3', dev: '/dev/sdd', fstype: 'xfs', mount_dir: '/db/mysql/redo' }
  - { vgname: 'vg3', disk: 'disklvm4', dev: '/dev/sde', fstype: 'xfs', mount_dir: '/backup'}

db_m_disk:
  - { vgname: 'vg0', disk: 'disklvm1', dev: '/dev/sdb', fstype: 'xfs', mount_dir: '/db/mysql/data'}
  - { vgname: 'vg1', disk: 'disklvm2', dev: '/dev/sdc', fstype: 'xfs', mount_dir: '/db/mysql/binlog'}
  - { vgname: 'vg2', disk: 'disklvm3', dev: '/dev/sdd', fstype: 'xfs', mount_dir: '/db/mysql/redo' }
  - { vgname: 'vg3', disk: 'disklvm4', dev: '/dev/sde', fstype: 'xfs', mount_dir: '/backup'}
  - { vgname: 'vg4', disk: 'disklvm5', dev: '/dev/sdf', fstype: 'xfs', mount_dir: '/game'}

redis_disk:
  - { vgname: 'vg0', disk: 'disklvm1', dev: '/dev/sdb', fstype: 'xfs', mount_dir: '/db/redis' }
  - { vgname: 'vg1', disk: 'disklvm2', dev: '/dev/sdc', fstype: 'xfs', mount_dir: '/backup'}

redis_m_disk:
  - { vgname: 'vg0', disk: 'disklvm1', dev: '/dev/sdb', fstype: 'xfs', mount_dir: '/db/redis' }
  - { vgname: 'vg1', disk: 'disklvm2', dev: '/dev/sdc', fstype: 'xfs', mount_dir: '/backup'}
  - { vgname: 'vg2', disk: 'disklvm3', dev: '/dev/sdd', fstype: 'xfs', mount_dir: '/mysql'}