- name: Get script NodeJS 10.x
  shell: "wget https://rpm.nodesource.com/setup_10.x -O /tmp/nodejs.sh"

- name: Chmod +x nodejs.sh
  file:
    path: "/tmp/nodejs.sh"
    mode: 0755

- name: NodeJS 10.x - Execute installation script
  shell: "/tmp/nodejs.sh"

- name: Install NodeJS
  yum :
    name: nodejs
    state: present

- name: Install pm2
  npm:
    name: pm2
    global: yes