---

- name: Install a list of packages for MySQL
  yum:
    name:
      - perl
      - net-tools
      - autoconf
    state: present

- name: Remove the mariadb-libs.x86_64 for MySQL
  yum:
    name: mariadb-libs.x86_64
    state: absent

- name: Install mysql-server-5.6.45
  yum:
    name: 
      - "{{ mysql_server_url }}"
      - "{{ mysql_client_url }}"
    state: present


- name: Template my.cnf.j2 to /etc/my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: mysql
    mode: 0644
  when:
    - label is not defined

- name: Template pika_my.cnf.j2 to /etc/my.cnf 
  template:
    src: pika_my.cnf.j2
    dest: /etc/my.cnf
    owner: mysql
    mode: 0644
  when:
    - label is defined

- name: Ensure /db/mysql/data own by mysql
  file:
    path: "{{ mysql_dir }}"
    state: directory
    owner: mysql
    group: mysql
    recurse: yes

- name: Init mysql
  command: mysql_install_db --defaults-file=/etc/my.cnf --user=mysql

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes