---
- hosts: common
  gather_facts: no
  tasks:
  # delete sudo user: yunwei
    - name: delete sudo user
      lineinfile: path=/etc/sudoers regexp=yunwei* state=absent

    - name: create user
      user: name=yunwei
    - name: set password for yunwei
      shell: "echo 'Yunwei@2018*.A' | passwd --stdin yunwei"     

    # copy sudoers file
    - name: add sudoers
      lineinfile: 
        path: /etc/sudoers 
        #regexp: "^yunwei"    
        line: 'yunwei ALL=(ALL) NOPASSWD:ALL'